import { AppService } from '../src/services/app-service.js';
import { IndexedDbRepository } from '../src/storage/indexed-db.js';
import { calculateAccumulated, calculateMonth, formatMoney, generateSummaryText } from '../src/domain/calculations.js';
import { datesInMonth, formatDate, formatMonth, monthKey, shiftMonth, toDateKey } from '../src/domain/dates.js';
import { pendingFixedDates } from '../src/domain/model.js';

const app = document.querySelector('#app');
const sheetRoot = document.querySelector('#sheet-root');
const toastElement = document.querySelector('#toast');
const service = new AppService(new IndexedDbRepository());
let view = { tab: 'calendar', month: monthKey(), selectedDate: toDateKey() };
const icons = { calendar: '▦', pending: '◷', payments: '₿', settings: '⚙︎' };
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const personName = id => service.state.people.find(person => person.id === id)?.name || 'Pessoa';
const centsFromInput = value => Math.round(Number(String(value).replace(',', '.')) * 100);

function applyTheme() {
  const theme = service.state.settings.theme;
  if (theme === 'system') document.documentElement.removeAttribute('data-theme'); else document.documentElement.dataset.theme = theme;
  const dark = theme === 'dark' || (theme === 'system' && matchMedia('(prefers-color-scheme: dark)').matches);
  document.querySelectorAll('meta[name=theme-color]').forEach(meta => meta.content = dark ? '#10161c' : '#f4f5f7');
}
function toast(message) { toastElement.textContent = message; toastElement.classList.add('show'); clearTimeout(toastElement.timer); toastElement.timer = setTimeout(() => toastElement.classList.remove('show'), 2600); }
function nav() { return `<nav class="tabbar" aria-label="Navegação principal">${[['calendar','Calendário'],['pending','Pendências'],['payments','Pagamentos'],['settings','Ajustes']].map(([key,label]) => `<button class="tab ${view.tab===key?'active':''}" data-tab="${key}" aria-current="${view.tab===key?'page':'false'}"><b>${icons[key]}</b>${label}</button>`).join('')}</nav>`; }
function header(eyebrow,title,action='') { return `<header class="topbar"><div><p class="eyebrow">${eyebrow}</p><h1 class="title">${title}</h1></div>${action}</header>`; }
function render() { const content=view.tab==='calendar'?calendarView():view.tab==='pending'?pendingView():view.tab==='payments'?paymentsView():settingsView(); app.innerHTML=`<main class="shell">${content}</main>${nav()}`; }

function calendarView() {
  const state=service.state,today=toDateKey(),todayPending=service.isFixed(today)&&!service.ride(today),summary=calculateMonth(state,view.month);
  const [year,month]=view.month.split('-').map(Number),firstDay=new Date(year,month-1,1,12).getDay(),cells=[...Array(firstDay).fill(null),...datesInMonth(view.month)],closed=state.closedMonths.includes(view.month),owner=personName(state.settings.ownerId);
  return `${header('Minha rotina','Corridas','<button class="icon-btn" data-action="month-summary" aria-label="Resumo do mês">↗</button>')}
  ${todayPending?`<div class="notice"><div><strong>Hoje ainda não foi preenchido</strong><span>Registre a corrida em poucos segundos.</span></div><button class="primary small" data-action="today-ride">Registrar</button></div>`:''}
  <section class="card calendar-card"><div class="month-nav"><button class="icon-btn" data-action="prev-month" aria-label="Mês anterior">‹</button><h2>${formatMonth(view.month)} ${closed?'<span class="badge">Fechado</span>':''}</h2><button class="icon-btn" data-action="next-month" aria-label="Próximo mês">›</button></div>
  <div class="today-row"><button class="pill-btn small" data-action="go-today">Hoje</button><div class="legend"><span><i class="dot done"></i>${escapeHtml(owner)}</span><span><i class="dot sub"></i>Substituto</span><span><i class="dot cancel"></i>Sem aula</span></div></div><div class="weekdays">${['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(day=>`<span>${day}</span>`).join('')}</div>
  <div class="calendar-grid">${cells.map(date=>{if(!date)return'<span class="day out"></span>';const ride=service.ride(date),fixed=service.isFixed(date),label=ride?(ride.status==='owner'?owner:ride.status==='substitute'?personName(ride.driverId):'Sem aula'):(fixed?'Pendente':'');const classes=['day',fixed?'fixed':'',fixed&&!ride&&date<=today?'pending':'',date===today?'today':'',date===view.selectedDate?'selected':'',ride?`status-${ride.status}`:'',ride?.extra?'extra':''].filter(Boolean).join(' ');return`<button class="${classes}" data-date="${date}" aria-label="${formatDate(date)}, ${label||'sem corrida'}"><span class="day-number">${Number(date.slice(-2))}</span><span class="day-label">${escapeHtml(label)}</span></button>`;}).join('')}</div>
  <div class="calendar-actions"><button class="secondary" data-action="fill-month" ${closed?'disabled':''}>Preencher mês</button><button class="primary" data-action="month-summary">Resumo do mês</button></div></section>
  <div class="section-title"><h2>Visão do mês</h2><p>${closed?'Fechamento protegido':'Em andamento'}</p></div><section class="stats"><div class="card stat"><strong>${summary.validCount}</strong><span>corridas válidas</span></div><div class="card stat"><strong>${formatMoney(summary.totalCents)}</strong><span>valor total</span></div><div class="card stat"><strong>${summary.substituteCount}</strong><span>substituições</span></div><div class="card stat"><strong>${summary.extraCount}</strong><span>extras</span></div></section>
  <div class="section-title"><h2>Rateio</h2><p>${summary.people.length} pessoas</p></div><section class="card">${summary.people.length?summary.people.map(row=>personRow(row,view.month)).join(''):'<div class="empty"><b>Nenhuma corrida registrada</b>Toque em um dia do calendário para começar.</div>'}</section>`;
}
function personRow(row,month='') { const status=row.balanceCents<=0?['paid','Quitado']:row.paidCents?['open','Parcial']:['open','Pendente'];return`<button class="person-row" data-person="${row.personId}" data-month="${month}"><span class="avatar">${escapeHtml(personName(row.personId).charAt(0))}</span><span class="row-main"><strong>${escapeHtml(personName(row.personId))}</strong><span>Base ${formatMoney(row.baseCents)}${row.creditCents?` · crédito ${formatMoney(row.creditCents)}`:''}</span></span><span class="amount">${formatMoney(row.balanceCents)}<small class="badge ${status[0]}">${status[1]}</small></span><span class="chevron">›</span></button>`; }
function pendingView() { const pending=pendingFixedDates(service.state),accounts=calculateAccumulated(service.state).filter(i=>i.balanceCents>0),open=accounts.reduce((s,i)=>s+i.balanceCents,0);return`${header('O que falta','Pendências')}<section class="card hero-balance"><span>Total financeiro em aberto</span><strong>${formatMoney(open)}</strong><span>${pending.length} ${pending.length===1?'dia para conferir':'dias para conferir'} · ${accounts.length} ${accounts.length===1?'pessoa':'pessoas'}</span></section><div class="section-title"><h2>Dias para conferir</h2><p>${pending.length}</p></div><section class="card">${pending.length?pending.slice().reverse().map(date=>`<button class="pending-row" data-pending-date="${date}"><span class="avatar">${date.slice(-2)}</span><span class="row-main"><strong>${formatDate(date)}</strong><span>Dia fixo ainda não preenchido</span></span><span class="chevron">›</span></button>`).join(''):'<div class="empty"><b>Tudo conferido</b>Não há dias fixos passados pendentes.</div>'}</section><div class="section-title"><h2>Valores em aberto</h2><p>${accounts.length}</p></div><section class="card">${accounts.length?accounts.map(i=>`<button class="person-row" data-person="${i.personId}"><span class="avatar">${escapeHtml(personName(i.personId).charAt(0))}</span><span class="row-main"><strong>${escapeHtml(personName(i.personId))}</strong><span>${i.months.filter(r=>r.balanceCents>0).length} meses em aberto</span></span><span class="amount">${formatMoney(i.balanceCents)}</span><span class="chevron">›</span></button>`).join(''):'<div class="empty"><b>Nenhum valor em aberto</b>Os pagamentos estão em dia.</div>'}</section>`; }
function paymentsView() { const accounts=calculateAccumulated(service.state).filter(i=>i.dueCents||i.paidCents),paid=service.state.payments.reduce((s,i)=>s+i.cents,0);return`${header('Movimentações','Pagamentos','<button class="icon-btn" data-action="new-payment" aria-label="Registrar pagamento">＋</button>')}<section class="stats"><div class="card stat"><strong>${formatMoney(accounts.reduce((s,i)=>s+Math.max(0,i.balanceCents),0))}</strong><span>saldo em aberto</span></div><div class="card stat"><strong>${formatMoney(paid)}</strong><span>total recebido</span></div></section><div class="section-title"><h2>Por pessoa</h2><p>${accounts.length}</p></div><section class="card">${accounts.length?accounts.map(i=>`<button class="person-row" data-person="${i.personId}"><span class="avatar">${escapeHtml(personName(i.personId).charAt(0))}</span><span class="row-main"><strong>${escapeHtml(personName(i.personId))}</strong><span>Pago ${formatMoney(i.paidCents)} de ${formatMoney(i.dueCents)}</span></span><span class="amount">${formatMoney(i.balanceCents)}</span><span class="chevron">›</span></button>`).join(''):'<div class="empty"><b>Sem movimentações</b>Os valores aparecem depois das primeiras corridas.</div>'}</section><div class="section-title"><h2>Histórico</h2><p>${service.state.payments.length}</p></div><section class="card">${service.state.payments.length?service.state.payments.slice().reverse().map(p=>`<button class="payment-row" data-payment="${p.id}"><span class="avatar">↓</span><span class="row-main"><strong>${escapeHtml(personName(p.personId))}</strong><span>${formatDate(p.date)}${p.note?` · ${escapeHtml(p.note)}`:''}</span></span><span class="amount">${formatMoney(p.cents)}</span><span class="chevron">›</span></button>`).join(''):'<div class="empty"><b>Nenhum pagamento</b>Registre pagamentos parciais ou a quitação total.</div>'}</section><button class="fab" data-action="new-payment" aria-label="Registrar pagamento">＋</button>`; }
function settingsView() { const s=service.state.settings;return`${header('Personalização','Ajustes')}<div class="section-title"><h2>Preferências</h2></div><section class="card"><button class="setting-row" data-action="settings-rides"><span class="avatar">↻</span><span class="row-main"><strong>Regras das corridas</strong><span>${s.fixedWeekdays.length} dias fixos · ${formatMoney(s.defaultFareCents)}</span></span><span class="chevron">›</span></button><button class="setting-row" data-action="settings-theme"><span class="avatar">◐</span><span class="row-main"><strong>Aparência</strong><span>${s.theme==='system'?'Sistema':s.theme==='light'?'Claro':'Escuro'}</span></span><span class="chevron">›</span></button></section><div class="section-title"><h2>Pessoas</h2><button class="pill-btn small" data-action="new-person">Adicionar</button></div><section class="card">${service.state.people.map(p=>`<button class="setting-row" data-edit-person="${p.id}"><span class="avatar">${escapeHtml(p.name.charAt(0))}</span><span class="row-main"><strong>${escapeHtml(p.name)}</strong><span>${p.active?'Ativa':'Inativa'}${p.joinedOn?` · desde ${formatDate(p.joinedOn)}`:''}</span></span><span class="chevron">›</span></button>`).join('')}</section><div class="section-title"><h2>Seus dados</h2></div><section class="card"><button class="setting-row" data-action="export-backup"><span class="avatar">⇩</span><span class="row-main"><strong>Exportar backup</strong><span>Baixar todos os dados em JSON</span></span></button><button class="setting-row" data-action="import-backup"><span class="avatar">⇧</span><span class="row-main"><strong>Importar backup</strong><span>Validar e restaurar um arquivo</span></span></button><input id="backup-file" type="file" accept="application/json,.json" hidden></section><p class="muted" style="text-align:center;font-size:.75rem;margin:18px">Dados salvos somente neste dispositivo · versão 1</p>`; }

function openSheet(content){sheetRoot.innerHTML=`<div class="sheet-backdrop"><section class="sheet" role="dialog" aria-modal="true"><div class="grabber"></div>${content}</section></div>`;document.body.style.overflow='hidden';sheetRoot.querySelector('.sheet-backdrop').addEventListener('click',e=>{if(e.target===e.currentTarget)closeSheet();});sheetRoot.querySelector('[autofocus]')?.focus();}
function closeSheet(){sheetRoot.innerHTML='';document.body.style.overflow='';}
const sheetHead=(title,subtitle='')=>`<div class="sheet-head"><div><h2>${title}</h2>${subtitle?`<p>${subtitle}</p>`:''}</div><button class="icon-btn" data-close aria-label="Fechar">×</button></div>`;
function openRideSheet(date){view.selectedDate=date;const ride=service.ride(date),fixed=service.isFixed(date),closed=service.state.closedMonths.includes(date.slice(0,7));if(!fixed&&!ride)return openSheet(`${sheetHead('Corrida extra',formatDate(date))}<p class="muted">Esse dia não faz parte da sua rotina semanal.</p><div class="sheet-actions single"><button class="primary" data-add-extra="${date}" ${closed?'disabled':''}>Adicionar corrida extra</button></div>${closed?'<p class="error-box">Reabra o mês para editar.</p>':''}`);const status=ride?.status||'',drivers=service.state.people.filter(p=>p.active&&p.id!==service.state.settings.ownerId);openSheet(`${sheetHead(ride?.extra?'Corrida extra':'Registrar corrida',formatDate(date))}${closed?'<p class="error-box">Este mês está fechado. Reabra para editar.</p>':''}<div class="choice-grid"><button class="choice ${status==='owner'?'active':''}" data-ride-status="owner" data-date="${date}" ${closed?'disabled':''}><span class="choice-icon">🚙</span><span><strong>Eu fui</strong><br><small class="muted">${escapeHtml(personName(service.state.settings.ownerId))} colocou o carro</small></span></button><button class="choice ${status==='substitute'?'active':''}" data-ride-status="substitute" data-date="${date}" ${closed?'disabled':''}><span class="choice-icon">↗</span><span><strong>Outra pessoa foi</strong><br><small class="muted">Gera crédito do valor da corrida</small></span></button><button class="choice ${status==='cancelled'?'active':''}" data-ride-status="cancelled" data-date="${date}" ${closed?'disabled':''}><span class="choice-icon">—</span><span><strong>Não teve corrida</strong><br><small class="muted">Sem aula ou dia cancelado</small></span></button></div>${status==='substitute'?`<div class="field" style="margin-top:14px"><label>Quem colocou o carro?</label><select id="ride-driver">${drivers.map(p=>`<option value="${p.id}" ${ride.driverId===p.id?'selected':''}>${escapeHtml(p.name)}</option>`).join('')}</select></div><div class="sheet-actions single"><button class="primary" data-save-driver="${date}">Salvar motorista</button></div>`:''}${ride&&!fixed?`<div class="divider"></div><button class="danger-btn" data-delete-ride="${date}" ${closed?'disabled':''}>Remover corrida extra</button>`:''}`);}
async function quickRide(date,status,driverId=null){const previous=service.ride(date);await service.saveRide({date,status,driverId,extra:previous?.extra||!service.isFixed(date)});toast('Corrida salva');render();openRideSheet(date);}
function openMonthSummary(){const s=calculateMonth(service.state,view.month),closed=service.state.closedMonths.includes(view.month);openSheet(`${sheetHead('Resumo do mês',formatMonth(view.month))}<section class="stats"><div class="card stat"><strong>${s.validCount}</strong><span>corridas</span></div><div class="card stat"><strong>${formatMoney(s.totalCents)}</strong><span>total</span></div></section><div class="divider"></div><div class="breakdown"><div class="breakdown-row"><span>${personName(service.state.settings.ownerId)} foi</span><strong>${s.ownerCount}</strong></div><div class="breakdown-row"><span>Substitutos</span><strong>${s.substituteCount}</strong></div><div class="breakdown-row"><span>Corridas extras</span><strong>${s.extraCount}</strong></div><div class="breakdown-row"><span>Sem aula</span><strong>${s.cancelledCount}</strong></div></div><div class="divider"></div>${s.people.map(r=>personRow(r,view.month)).join('')||'<p class="muted">Nenhum valor calculado.</p>'}<div class="sheet-actions"><button class="secondary" data-action="share-summary">Gerar resumo</button><button class="${closed?'secondary':'primary'}" data-toggle-month>${closed?'Reabrir mês':'Fechar mês'}</button></div>`);}
function openShareSheet(){const text=generateSummaryText(service.state,view.month);openSheet(`${sheetHead('Resumo para compartilhar',formatMonth(view.month))}<div class="share-text">${escapeHtml(text)}</div><div class="sheet-actions"><button class="secondary" data-copy-summary>Copiar texto</button><button class="primary" data-share-summary>Compartilhar</button></div>`);}
function openFillSheet(){const dates=datesInMonth(view.month).filter(d=>d<=toDateKey()&&service.isFixed(d)&&!service.ride(d));openSheet(`${sheetHead('Preencher dias fixos',formatMonth(view.month))}<p>${dates.length?`${dates.length} ${dates.length===1?'dia será marcado':'dias serão marcados'} como “${escapeHtml(personName(service.state.settings.ownerId))} foi”.`:'Todos os dias fixos desse mês já foram preenchidos.'}</p><p class="muted">Registros existentes serão preservados.</p><div class="sheet-actions"><button class="secondary" data-close>Cancelar</button><button class="primary" data-confirm-fill ${dates.length?'':'disabled'}>Preencher ${dates.length}</button></div>`);}
function openPersonDetail(personId,month=''){const account=calculateAccumulated(service.state).find(i=>i.personId===personId),rows=month?(account?.months.filter(i=>i.month===month)||[]):(account?.months||[]),balance=rows.reduce((s,r)=>s+r.balanceCents,0),payments=service.state.payments.filter(p=>p.personId===personId);openSheet(`${sheetHead(escapeHtml(personName(personId)),month?formatMonth(month):'Composição acumulada')}<div class="card hero-balance"><span>Saldo restante</span><strong>${formatMoney(balance)}</strong><span>Total ${formatMoney(rows.reduce((s,r)=>s+r.dueCents,0))} · Pago ${formatMoney(rows.reduce((s,r)=>s+r.paidCents,0))}</span></div><div class="section-title"><h2>Por mês</h2></div><div class="breakdown">${rows.map(r=>`<div class="card"><div class="breakdown-row total-row"><span>${formatMonth(r.month)}</span><strong>${formatMoney(r.balanceCents)}</strong></div><div class="breakdown-row"><span>Valor base</span><b>${formatMoney(r.baseCents)}</b></div>${r.creditCents?`<div class="breakdown-row"><span>Créditos</span><b>− ${formatMoney(r.creditCents)}</b></div>`:''}<div class="breakdown-row"><span>Pago</span><b>${formatMoney(r.paidCents)}</b></div>${r.entries.filter(e=>e.kind==='credit').map(e=>`<div class="breakdown-row"><span>${formatDate(e.date)} · motorista</span><b>− ${formatMoney(e.cents)}</b></div>`).join('')}</div>`).join('')||'<p class="muted">Sem lançamentos.</p>'}</div>${balance>0?`<div class="sheet-actions"><button class="secondary" data-pay-person="${personId}" data-pay-full="${balance}">Dar baixa total</button><button class="primary" data-pay-person="${personId}">Registrar pagamento</button></div>`:''}${payments.length?`<div class="section-title"><h2>Pagamentos</h2></div>${payments.map(p=>`<button class="payment-row" data-payment="${p.id}"><span class="row-main"><strong>${formatDate(p.date)}</strong><span>${p.allocations.map(a=>formatMonth(a.month)).join(', ')}</span></span><span class="amount">${formatMoney(p.cents)}</span><span class="chevron">›</span></button>`).join('')}`:''}`);}
function openPaymentForm(personId='',fullCents=0,paymentId=''){const payment=service.state.payments.find(i=>i.id===paymentId),selected=payment?.personId||personId,copy=payment?{...service.state,payments:service.state.payments.filter(i=>i.id!==payment.id)}:service.state,account=selected?calculateAccumulated(copy).find(i=>i.personId===selected):null,openMonths=account?.months.filter(r=>r.balanceCents>0)||[];openSheet(`${sheetHead(payment?'Editar pagamento':'Registrar pagamento','Pagamento parcial ou quitação')}<form id="payment-form" class="form"><input type="hidden" name="id" value="${payment?.id||''}"><div class="field"><label>Pessoa</label><select name="personId" required ${payment?'disabled':''}><option value="">Selecione</option>${service.state.people.map(p=>`<option value="${p.id}" ${selected===p.id?'selected':''}>${escapeHtml(p.name)}</option>`).join('')}</select></div><div class="field"><label>Valor</label><input name="amount" type="number" inputmode="decimal" min="0.01" step="0.01" value="${((payment?.cents||fullCents)/100||'').toString()}" required></div><div class="field"><label>Data</label><input name="date" type="date" value="${payment?.date||toDateKey()}" required></div><div class="field"><label>Aplicação</label><select name="mode"><option value="oldest">Meses mais antigos primeiro</option><option value="manual">Escolher manualmente</option></select></div><div id="manual-allocations" hidden class="manual-grid">${openMonths.map(r=>`<label class="manual-line"><span>${formatMonth(r.month)} · falta ${formatMoney(r.balanceCents)}</span><input data-allocation="${r.month}" type="number" min="0" max="${r.balanceCents/100}" step="0.01" value="0"></label>`).join('')}</div><div class="field"><label>Observação opcional</label><textarea name="note">${escapeHtml(payment?.note||'')}</textarea></div><div id="payment-error"></div><div class="sheet-actions"><button type="button" class="secondary" data-close>Cancelar</button><button class="primary" type="submit">Salvar</button></div></form>`);}
function openPaymentDetail(id){const p=service.state.payments.find(i=>i.id===id);if(!p)return;openSheet(`${sheetHead('Pagamento',personName(p.personId))}<div class="card hero-balance"><span>Valor recebido</span><strong>${formatMoney(p.cents)}</strong><span>${formatDate(p.date)}</span></div>${p.note?`<p>${escapeHtml(p.note)}</p>`:''}<div class="section-title"><h2>Aplicado em</h2></div><div class="breakdown">${p.allocations.map(i=>`<div class="breakdown-row"><span>${formatMonth(i.month)}</span><strong>${formatMoney(i.cents)}</strong></div>`).join('')}</div><div class="sheet-actions"><button class="danger-btn" data-delete-payment="${id}">Excluir</button><button class="secondary" data-edit-payment="${id}">Editar</button></div>`);}
function openPersonForm(id=''){const p=service.state.people.find(i=>i.id===id);openSheet(`${sheetHead(p?'Editar pessoa':'Nova pessoa')}<form id="person-form" class="form"><input name="id" type="hidden" value="${p?.id||''}"><div class="field"><label>Nome</label><input name="name" value="${escapeHtml(p?.name||'')}" required autofocus></div><div class="field"><label>Entrada no grupo (opcional)</label><input name="joinedOn" type="date" value="${p?.joinedOn||''}"></div><label class="check-row"><span>Participa das novas corridas</span><input class="switch" name="active" type="checkbox" ${p?.active!==false?'checked':''}></label><p class="muted">Desativar preserva todas as corridas e valores históricos.</p><div class="sheet-actions"><button type="button" class="secondary" data-close>Cancelar</button><button class="primary">Salvar</button></div></form>`);}
function openRideSettings(){const s=service.state.settings;openSheet(`${sheetHead('Regras das corridas')}<form id="ride-settings" class="form"><div class="field"><label>Valor padrão por corrida</label><input name="fare" type="number" inputmode="decimal" min="0.01" step="0.01" value="${s.defaultFareCents/100}" required></div><div class="field"><label>Dias fixos</label><div class="week-picker">${['D','S','T','Q','Q','S','S'].map((label,index)=>`<label><input type="checkbox" name="weekday" value="${index}" ${s.fixedWeekdays.includes(index)?'checked':''}><span>${label}</span></label>`).join('')}</div></div><p class="muted">Alterações valem para novos registros. Corridas antigas mantêm o valor e os participantes originais.</p><div class="sheet-actions"><button type="button" class="secondary" data-close>Cancelar</button><button class="primary">Salvar</button></div></form>`);}
function openThemeSettings(){const current=service.state.settings.theme;openSheet(`${sheetHead('Aparência')}<div class="choice-grid">${[['system','◐','Sistema'],['light','☀','Claro'],['dark','●','Escuro']].map(([key,icon,label])=>`<button class="choice ${current===key?'active':''}" data-theme-choice="${key}"><span class="choice-icon">${icon}</span><strong>${label}</strong></button>`).join('')}</div>`);}
async function exportBackup(){const blob=new Blob([JSON.stringify(service.exportBackup(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`corridas-backup-${toDateKey()}.json`;link.click();URL.revokeObjectURL(url);toast('Backup exportado');}
async function importFile(file){try{const value=JSON.parse(await file.text()),data=(await import('../src/services/backup.js')).validateBackup(value);openSheet(`${sheetHead('Restaurar backup')}<p>O arquivo contém <strong>${data.people.length} pessoas</strong>, <strong>${data.rides.length} corridas</strong> e <strong>${data.payments.length} pagamentos</strong>.</p><p class="error-box">A restauração substituirá os dados atuais neste dispositivo.</p><div class="sheet-actions"><button class="secondary" data-close>Cancelar</button><button class="primary" id="confirm-import">Restaurar</button></div>`);document.querySelector('#confirm-import').onclick=async()=>{await service.importBackup(value);applyTheme();closeSheet();render();toast('Backup restaurado');};}catch(error){toast(error.message||'Arquivo inválido');}}

app.addEventListener('click',async event=>{const target=event.target.closest('button,[data-date]');if(!target)return;try{if(target.dataset.tab){view.tab=target.dataset.tab;render();return;}if(target.dataset.date)return openRideSheet(target.dataset.date);if(target.dataset.person)return openPersonDetail(target.dataset.person,target.dataset.month||'');if(target.dataset.pendingDate){view.month=target.dataset.pendingDate.slice(0,7);view.tab='calendar';render();openRideSheet(target.dataset.pendingDate);return;}if(target.dataset.payment)return openPaymentDetail(target.dataset.payment);if(target.dataset.editPerson)return openPersonForm(target.dataset.editPerson);const action=target.dataset.action;if(action==='prev-month'){view.month=shiftMonth(view.month,-1);render();}if(action==='next-month'){view.month=shiftMonth(view.month,1);render();}if(action==='go-today'){view.month=monthKey();view.selectedDate=toDateKey();render();}if(action==='today-ride')openRideSheet(toDateKey());if(action==='month-summary')openMonthSummary();if(action==='fill-month')openFillSheet();if(action==='new-payment')openPaymentForm();if(action==='new-person')openPersonForm();if(action==='settings-rides')openRideSettings();if(action==='settings-theme')openThemeSettings();if(action==='export-backup')exportBackup();if(action==='import-backup')document.querySelector('#backup-file').click();}catch(error){toast(error.message);}});
sheetRoot.addEventListener('click',async event=>{const target=event.target.closest('button');if(!target)return;try{if(target.hasAttribute('data-close'))return closeSheet();if(target.dataset.addExtra){await quickRide(target.dataset.addExtra,'owner');return;}if(target.dataset.rideStatus){const date=target.dataset.date,status=target.dataset.rideStatus;if(status==='substitute'){const driver=service.state.people.find(p=>p.active&&p.id!==service.state.settings.ownerId);await quickRide(date,status,driver?.id);}else await quickRide(date,status);return;}if(target.dataset.saveDriver){await quickRide(target.dataset.saveDriver,'substitute',document.querySelector('#ride-driver').value);return;}if(target.dataset.deleteRide){if(confirm('Remover esta corrida extra?')){await service.deleteRide(target.dataset.deleteRide);closeSheet();render();toast('Corrida removida');}return;}if(target.hasAttribute('data-confirm-fill')){const dates=await service.fillMonth(view.month,toDateKey());closeSheet();render();toast(`${dates.length} dias preenchidos`);return;}if(target.hasAttribute('data-toggle-month')){if(confirm(service.state.closedMonths.includes(view.month)?'Reabrir este mês para edição?':'Fechar o mês e proteger os registros?')){await service.toggleMonth(view.month);closeSheet();render();toast('Status do mês atualizado');}return;}if(target.dataset.action==='share-summary')return openShareSheet();if(target.hasAttribute('data-copy-summary')){await navigator.clipboard.writeText(generateSummaryText(service.state,view.month));toast('Resumo copiado');return;}if(target.hasAttribute('data-share-summary')){const text=generateSummaryText(service.state,view.month);if(navigator.share)await navigator.share({title:`Corridas — ${formatMonth(view.month)}`,text});else{await navigator.clipboard.writeText(text);toast('Resumo copiado');}return;}if(target.dataset.person)return openPersonDetail(target.dataset.person,target.dataset.month||'');if(target.dataset.payment)return openPaymentDetail(target.dataset.payment);if(target.dataset.payPerson)return openPaymentForm(target.dataset.payPerson,Number(target.dataset.payFull)||0);if(target.dataset.editPayment)return openPaymentForm('','',target.dataset.editPayment);if(target.dataset.deletePayment){if(confirm('Excluir este pagamento?')){await service.deletePayment(target.dataset.deletePayment);closeSheet();render();toast('Pagamento excluído');}return;}if(target.dataset.themeChoice){await service.saveSettings({theme:target.dataset.themeChoice});applyTheme();closeSheet();render();return;}}catch(error){toast(error.message||'Não foi possível concluir');}});
sheetRoot.addEventListener('change',event=>{if(event.target.name==='mode')document.querySelector('#manual-allocations').hidden=event.target.value!=='manual';if(event.target.name==='personId'&&event.target.closest('#payment-form'))openPaymentForm(event.target.value);});
sheetRoot.addEventListener('submit',async event=>{event.preventDefault();const form=event.target,formId=form.getAttribute('id'),data=new FormData(form);try{if(formId==='person-form')await service.savePerson({id:data.get('id'),name:data.get('name'),joinedOn:data.get('joinedOn'),active:data.has('active')});if(formId==='ride-settings'){const days=data.getAll('weekday').map(Number);if(!days.length)throw new Error('Escolha pelo menos um dia fixo.');await service.saveSettings({defaultFareCents:centsFromInput(data.get('fare')),fixedWeekdays:days});}if(formId==='payment-form'){const personId=data.get('personId')||form.querySelector('[name=personId]').value,allocations=[...form.querySelectorAll('[data-allocation]')].map(input=>({month:input.dataset.allocation,cents:centsFromInput(input.value)}));await service.addPayment({id:data.get('id')||null,personId,cents:centsFromInput(data.get('amount')),date:data.get('date'),note:data.get('note'),mode:data.get('mode'),allocations});}closeSheet();render();toast('Alterações salvas');}catch(error){const box=form.querySelector('#payment-error');if(box){box.className='error-box';box.textContent=error.message;}else toast(error.message);}});
app.addEventListener('change',event=>{if(event.target.id==='backup-file'&&event.target.files[0])importFile(event.target.files[0]);});
matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(service.state?.settings.theme==='system')applyTheme();});
try{await service.init();applyTheme();render();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./service-worker.js').catch(error=>console.error('Service worker:',error));}catch(error){app.innerHTML=`<div class="boot"><strong>Não foi possível abrir o aplicativo</strong><span>${escapeHtml(error.message)}</span></div>`;console.error(error);}
